### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KhurramJalil**
Updated README.md file to replace the term "apis.json folder" with "apis.json file" as it's a JSON file rather than a folder.

Also hyperlinked the apis.json file to the corresponding JSON file in the same nasa/api-docs git repo for easy access to all users.

### CODE REVIEW

**Comment by KhurramJalil** [comment]
@jasonduley, @rubioJeffery, @evantayloryates, @danhammer, @jmhorn2015, @darith27, @drbitboy, @corincerami, @jnbetancourt, @nwunderly, @TKantz and @JustinGOSSES Can you please review / approve / merge this PR?

**Comment by drbitboy** [comment]
I don't have a button to review this PR, but it does "LGTM!"

**Review by drbitboy — APPROVED** [review]
the updated link worked for me.

**Comment by KhurramJalil** [comment]
> the updated link worked for me.

Thanks @drbitboy for reviewing the changes.

For me, "merging is blocked" i.e. I am not authorized to merge the changes of my PR into the nasa:gh-pages branch so can you please do the needful to merge my PR into the nasa:gh-pages branch?

**Comment by KhurramJalil** [comment]
@jasonduley, @rubioJeffery, @evantayloryates, @danhammer, @jmhorn2015, @darith27, @drbitboy, @corincerami, @jnbetancourt, @nwunderly, @TKantz and @JustinGOSSES Now that the PR has been reviewed/approved, can anyone of you please do the needful & merge this PR?

**Comment by KhurramJalil** [comment]
@jasonduley, @rubioJeffery, @evantayloryates, @danhammer, @jmhorn2015, @darith27, @drbitboy, @corincerami, @jnbetancourt, @nwunderly, @TKantz and @JustinGOSSES!

Now that @drbitboy has reviewed / approved the changes in this PR, can some authorized person please do the needful to merge it to the appropriate branch so the fix goes live?

For me "Merging is blocked" as I'm not authorized to merge this pull request.

**Comment by nwunderly** [comment]
My friend, I'm not sure anyone you're pinging has the ability or responsibility to merge anymore. I'm not a maintainer, just a contributor, and it appears that Justin (who had previously been maintaining this) has left NASA. Please check who you're actually trying to ping and whether they have any ability to do anything as you're bothering like ten people on a weekly basis.

**Comment by KhurramJalil** [comment]
Thanks @TKantz

**Pull request merged**
