### PR TITLE
Update apis.json

### LINKED ISSUE #173: Broken Links to SSCWeb
The links to [Satellite Situation Center Web (SSCWeb) service](https://sscweb.sci.gsfc.nasa.gov/WebServices/REST/) are broken, giving "Name not resolved / IP address not found" errors.

Both the link with text "Satellite Situation Center Web (SSCWeb) service" and "visit this page." are broken.

### PR DESCRIPTION
**Pull request by KhurramJalil**
Fixed #173 and #192 by updating both the broken links to correct URLs

### CODE REVIEW

**Comment by KhurramJalil** [comment]
@jasonduley, @rubioJeffery, @evantayloryates, @danhammer, @jmhorn2015, @darith27, @drbitboy, @corincerami, @jnbetancourt, @nwunderly, @TKantz and @JustinGOSSES please review/approve/merge this PR as it fixes both the issues #173 and #192

**Review by drbitboy — APPROVED** [review]
the links worked for me.

**Comment by KhurramJalil** [comment]
> the links worked for me.

Thanks @drbitboy for reviewing the changes.

For me, "merging is blocked" i.e. I am not authorized to merge the changes of my PR into the nasa:gh-pages branch so can you please do the needful to merge my PR into the nasa:gh-pages branch?

**Comment by KhurramJalil** [comment]
@jasonduley, @rubioJeffery, @evantayloryates, @danhammer, @jmhorn2015, @darith27, @drbitboy, @corincerami, @jnbetancourt, @nwunderly, @TKantz and @JustinGOSSES Now that the PR has been reviewed/approved, can anyone of you please do the needful & merge this PR?

**Comment by KhurramJalil** [comment]
@jasonduley, @rubioJeffery, @evantayloryates, @danhammer, @jmhorn2015, @darith27, @drbitboy, @corincerami, @jnbetancourt, @nwunderly, @TKantz and @JustinGOSSES!

Now that @drbitboy has reviewed / approved the changes in this PR, can some authorized person please do the needful to merge it to the appropriate branch so the fix goes live?

For me "Merging is blocked" as I'm not authorized to merge this pull request.

**Comment by KhurramJalil** [comment]
@jasonduley, @rubioJeffery, @evantayloryates, @danhammer, @jmhorn2015, @darith27, @drbitboy, @corincerami, @jnbetancourt, @nwunderly, @TKantz and @JustinGOSSES!

Now that @drbitboy has reviewed / approved the changes in this PR, can some authorized person please do the needful to merge it to the appropriate branch so the fix goes live?

For me "Merging is blocked" as I'm not authorized to merge this pull request.

**Comment by nwunderly** [comment]
My friend, I'm not sure anyone you're pinging has the ability or responsibility to merge anymore. I'm not a maintainer, just a contributor, and it appears that Justin (who had previously been maintaining this) has left NASA. Please check who you're actually trying to ping and whether they have any ability to do anything as you're bothering like ten people on a weekly basis.

**Review by TKantz — APPROVED** [review]

**Comment by TKantz** [comment]
Pull request approved and completed.

**Comment by KhurramJalil** [comment]
> Pull request approved and completed.

Thanks @TKantz

**Comment by Victor-Lockwood** [comment]
It looks like these changes got reverted/overwritten at some point - the links are broken in prod again.

**Comment by KhurramJalil** [comment]
@TKantz @darith27 Can you please look into the issue mentioned by @Victor-Lockwood above where it seems like that my changes above for fixing both the broken links in file "assets/json/api.json" somehow got reverted or overwritten?

**Pull request merged**
