### PR TITLE
[WIP] Setup Tools to build the API site

### PR DESCRIPTION
**Pull request by evenstensberg**
Curently fails bc of https://github.com/middleman/middleman/issues/1300

Could someone pick this up? Is this repo maintained? Where's https://api.nasa.gov/ built from?

### CODE REVIEW

**Comment by JustinGOSSES** [comment]
api.nasa.gov is built from gh-pages. We are in the early stages of putting it though a complete revamp.

**Comment by evenstensberg** [comment]
Awesome. Having a thread with some folks regarding the api hosted at https://sscweb.sci.gsfc.nasa.gov/ . Do you want me to CC you in? Think it'll be good for alignment

**Comment by JustinGOSSES** [comment]
Well, to be clear, we don't actually host any APIs or have edit powers on any of them. API.nasa.gov is just a pass through clearinghouse. In general, if an API listed on api.nasa.gov we appreciate updates to our documentation and getting started language for that api. If it is something else, it probably doesn't impact Api.nasa.gov. I'm not sure what the thread is about, so not sure how relevant?

**Comment by evenstensberg** [comment]
This thread is about improving the API docs at Goddard, which is why I was introduced to this repository. Relevant in terms of making that API a resource at this repo.

**Comment by JustinGOSSES** [comment]
Please add myself & @evantayloryates to that thread in that case, thank you.

**Comment by jmhorn2015** [comment]
Revamp of api.nasa.gov leaves this pull outdated. Closing request.

**Pull request closed without merging**
