### PR TITLE
Add example HTML/Javascript to generate wind rose from InSight data

### PR DESCRIPTION
**Pull request by drbitboy**
in api.html, /drbitboy/ will need to be changed to /nasa/
...
Never mind, changed it to /nasa/ in the PR.

### CODE REVIEW

**Comment by JustinGOSSES** [comment]
Thanks @drbitboy we're actually about to deploy an entirely new version of api.nasa.gov , so I'll hold off on integrating this pull request for now. 

I did look at your code and have 4 requests for changes you could make in the meantime. 

1.) Change the links to images and html files to be references not strict. For example, change `https://github.com/nasa/api-docs/blob/gh-pages/examples/insight_mars_wind_rose.html` to  `/examples/insight_mars_wind_rose.html`. This makes it easier to take a look at things locally and if we shift things around in the future. 

2.) Narrow the screenshot image of the rose diagram to just include the rose diagram and not the rest of the page. 

3.) Explicitly limit the screenshot of the rose to something smaller. With no explicit size, it comes in as full page width. 

4.) When your rose diagram demo page first comes up, there is no rose diagram. I had to click on a sol button first. _That was confusing._ Please change it such that the first sol is selected for the rose diagram on load. 

Thanks again. We'll likely have the new version up by end of this week or early next. At which time we'll consider adding in this code. Ping us here if the code isn't added in.

**Comment by JustinGOSSES** [comment]
tagging @jmhorn2015 as she is working on the new api.nasa.gov

**Comment by drbitboy** [comment]
1.) do you mean example/... or ./example/..., and not /example/... i.e. not absolute?
1.) I have to comment out line 20 to use api.html locally e.g. file:///home/me/whatever/api-docs/api.html

**Comment by JustinGOSSES** [comment]
> 1.) do you mean example/... or ./example/..., and not /example/... i.e. not absolute?
> 1.) I have to comment out line 20 to use api.html locally e.g. file:///home/me/whatever/api-docs/api.html

1. Not absolute if I understand you correctly (though you might have to still with your absolute given # 2
2. Yes, I have to do this as well. I comment out lines 14-22 while testing and then uncomment when go live.

**Comment by drbitboy** [comment]
Changing line 20 to this

            else if (window.location.protocol != "https:"
                  && window.location.protocol != "file:"  // Avoid https
when browsing locally as file:///...
                    ) {


allows us to test it locally as file:///.../api.html.

I am putting that into the PR.

Brian Carcich

**Comment by drbitboy** [comment]
> Thanks @drbitboy [...] 1 ...  2 ... 3 ... 4.
> We'll likely have the new version up by end of this week or early next. At which time we'll consider adding in this code. Ping us here if the code isn't added in.

Done.

**Comment by jmhorn2015** [comment]
Hi Brian! We started storing all of our API info in a .json file, so I copied over your changes manually. The wind rose is now live on api.nasa.gov!

Jenna Horn

**Comment by drbitboy** [comment]
Very nice!

**Pull request closed without merging**
